[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nixpkgs = "python311"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "gcc"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install --no-cache-dir -r requirements-prod.txt"]

[build.nixpacksPlan.start]
cmd = "gunicorn app_flask:app"
